# Generated by Django 6.1.1 on 2026-09-30 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['switch', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='IDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('INTERIOR', 'Interior'), ('EXTERIOR', 'Exterior'), ('CORE', 'Core')], default='INTERIOR', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.nivel')),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('INHABILITADO', 'Inhabilitado')], default='ACTIVO', max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('Computadora', 'Computadora'), ('Impresora', 'Impresora'), ('Camara', 'Cámara'), ('Telefono', 'Teléfono'), ('WiFi', 'Access Point WiFi'), ('Switch', 'Switch (Cascada)'), ('Biomedico', 'Equipo Biomédico'), ('Copiadora', 'Copiadora'), ('Reloj Checador', 'Reloj Checador'), ('Otro', 'Otro')], max_length=40)),
                ('ip', models.CharField(blank=True, max_length=80)),
                ('nombre_equipo', models.CharField(blank=True, max_length=200)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('observacion', models.TextField(blank=True)),
                ('puerto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodo', to='inventario.puerto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('total_puertos', models.PositiveIntegerField(default=24)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('idf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='inventario.idf')),
            ],
            options={
                'verbose_name_plural': 'Switches',
                'ordering': ['idf', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='puerto',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='inventario.switch'),
        ),
        migrations.AddField(
            model_name='puerto',
            name='vlans',
            field=models.ManyToManyField(blank=True, related_name='puertos', to='inventario.vlan'),
        ),
        migrations.AlterUniqueTogether(
            name='puerto',
            unique_together={('switch', 'numero')},
        ),
    ]
